location /api0 { proxy_pass http://127.0.0.1:8000; }
location /api1 { proxy_pass http://127.0.0.1:8001; }
location /api2 { proxy_pass http://127.0.0.1:8002; }
location /api3 { proxy_pass http://127.0.0.1:8003; }
location /api4 { proxy_pass http://127.0.0.1:8004; }
location /api5 { proxy_pass http://127.0.0.1:8005; }
location /api6 { proxy_pass http://127.0.0.1:8006; }
location /api7 { proxy_pass http://127.0.0.1:8007; }
location /api8 { proxy_pass http://127.0.0.1:8008; }
location /api9 { proxy_pass http://127.0.0.1:8009; }
location /api10 { proxy_pass http://127.0.0.1:8010; }
location /api11 { proxy_pass http://127.0.0.1:8011; }
location /api12 { proxy_pass http://127.0.0.1:8012; }
location /api13 { proxy_pass http://127.0.0.1:8013; }
location /api14 { proxy_pass http://127.0.0.1:8014; }
location /api15 { proxy_pass http://127.0.0.1:8015; }
location /api16 { proxy_pass http://127.0.0.1:8016; }
location /api17 { proxy_pass http://127.0.0.1:8017; }
location /api18 { proxy_pass http://127.0.0.1:8018; }
location /api19 { proxy_pass http://127.0.0.1:8019; }
location /api20 { proxy_pass http://127.0.0.1:8020; }
location /api21 { proxy_pass http://127.0.0.1:8021; }
location /api22 { proxy_pass http://127.0.0.1:8022; }
location /api23 { proxy_pass http://127.0.0.1:8023; }
location /api24 { proxy_pass http://127.0.0.1:8024; }
location /api25 { proxy_pass http://127.0.0.1:8025; }
location /api26 { proxy_pass http://127.0.0.1:8026; }
location /api27 { proxy_pass http://127.0.0.1:8027; }
location /api28 { proxy_pass http://127.0.0.1:8028; }
location /api29 { proxy_pass http://127.0.0.1:8029; }
location /api30 { proxy_pass http://127.0.0.1:8030; }
location /api31 { proxy_pass http://127.0.0.1:8031; }
location /api32 { proxy_pass http://127.0.0.1:8032; }
location /api33 { proxy_pass http://127.0.0.1:8033; }
location /api34 { proxy_pass http://127.0.0.1:8034; }
location /api35 { proxy_pass http://127.0.0.1:8035; }
location /api36 { proxy_pass http://127.0.0.1:8036; }
location /api37 { proxy_pass http://127.0.0.1:8037; }
location /api38 { proxy_pass http://127.0.0.1:8038; }
location /api39 { proxy_pass http://127.0.0.1:8039; }
location /api40 { proxy_pass http://127.0.0.1:8040; }
location /api41 { proxy_pass http://127.0.0.1:8041; }
location /api42 { proxy_pass http://127.0.0.1:8042; }
location /api43 { proxy_pass http://127.0.0.1:8043; }
location /api44 { proxy_pass http://127.0.0.1:8044; }
location /api45 { proxy_pass http://127.0.0.1:8045; }
location /api46 { proxy_pass http://127.0.0.1:8046; }
location /api47 { proxy_pass http://127.0.0.1:8047; }
location /api48 { proxy_pass http://127.0.0.1:8048; }
location /api49 { proxy_pass http://127.0.0.1:8049; }
location /api50 { proxy_pass http://127.0.0.1:8050; }
location /api51 { proxy_pass http://127.0.0.1:8051; }
location /api52 { proxy_pass http://127.0.0.1:8052; }
location /api53 { proxy_pass http://127.0.0.1:8053; }
location /api54 { proxy_pass http://127.0.0.1:8054; }
location /api55 { proxy_pass http://127.0.0.1:8055; }
location /api56 { proxy_pass http://127.0.0.1:8056; }
location /api57 { proxy_pass http://127.0.0.1:8057; }
location /api58 { proxy_pass http://127.0.0.1:8058; }
location /api59 { proxy_pass http://127.0.0.1:8059; }
